"""Service for AI-powered tasks like generating commit messages and Pull Request metadata."""

import os
from vlooper.config import config
from vlooper.core.exceptions import VLooperError
from vlooper.clients.git_client import has_uncommitted_changes
from vlooper.clients.opencode_client import OpencodeClient
from vlooper.infra.logger import get_logger

logger = get_logger(__name__)


def generate_commit_message(repo_dir: str, issue_number: int) -> str:
    """Generates a concise commit message based on git diff using an LLM."""
    if not has_uncommitted_changes(repo_dir):
        return f"fix: automated fix for issue #{issue_number}"

    logger.info("🤖 Generating AI-powered commit message...")

    # 1. Get the git diff
    from vlooper.infra.utils import run_command
    stdout, err = run_command(["git", "diff"], cwd=repo_dir)
    if err:
        logger.error("Failed to get git diff: %s", err)
        return f"fix: automated fix for issue #{issue_number}"

    if not stdout or not stdout.strip():
        return f"fix: automated fix for issue #{issue_number}"

    # 2. Prepare the prompt
    prompt = (
        f"Write ONLY a single-line, concise commit message in conventional commits format "
        f"for the following git diff. Do not include any explanations or extra text:\n\n"
        f"{stdout[:4000]}"  # Limit diff size to avoid huge prompts
    )

    # 3. Call Opencode agent via Client
    client = OpencodeClient()
    try:
        result, err = client.run(prompt, cwd=repo_dir)

        if err:
            logger.warning("AI commit message generation failed: %s. Using fallback.", err)
            return f"fix: automated fix for issue #{issue_number}"

        # 4. Clean up the result
        # The agent might output more than just one line, so we take the first non-empty line
        lines = [line.strip() for line in result.splitlines() if line.strip()]
        if lines:
            # Take the first line as the commit message
            commit_msg = lines[0]
            # Remove common prefixes if the agent added them like "Commit message: ..."
            if ":" in commit_msg and len(commit_msg.split(":")[0]) < 20:
                commit_msg = commit_msg.split(":", 1)[1].strip()

            logger.info("✨ Generated AI commit message: %s", commit_msg)
            return commit_msg

    except Exception as e:
        logger.error("Error during AI commit message generation: %s", e)

    return f"fix: automated fix for issue #{issue_number}"


def generate_pr_metadata(repo_dir: str, issue_number: int, task_id: str) -> tuple[str, str]:
    """Generates a Pull Request title and body based on git diff using an LLM."""
    logger.info("🤖 Generating AI-powered PR metadata...")

    # 1. Get the git diff
    from vlooper.infra.utils import run_command
    stdout, err = run_command(["git", "diff"], cwd=repo_dir)
    if err:
        logger.error("Failed to get git diff for PR generation: %s", err)
        return f"Fix issue #{issue_number}", f"Automated fix generated by vLooper for task {task_id}."

    if not stdout or not stdout.strip():
        return f"Fix issue #{issue_number}", f"Automated fix generated by vLooper for task {task_id}."

    # 2. Prepare the prompt
    prompt = (
        f"Based on the following git diff for issue #{issue_number}, generate a concise "
        f"Pull Request title and a short description of the changes. "
        f"Return your response in exactly this format:\n\n"
        f"TITLE: [Your generated title]\n"
        f"BODY: [Your generated body]\n\n"
        f"Do not include any other text, explanations or conversational filler.\n\n"
        f"Diff:\n{stdout[:5000]}"
    )

    # 3. Call Opencode agent via Client
    client = OpencodeClient()
    try:
        result, err = client.run(prompt, cwd=repo_dir)

        if err:
            logger.warning("AI PR metadata generation failed: %s. Using fallback.", err)
            return f"Fix issue #{issue_number}", f"Automated fix generated by vLooper for task {task_id}."

        # 4. Parse the result
        lines = [line.strip() for line in result.splitlines() if line.strip()]
        title, body = None, None

        for i, line in enumerate(lines):
            if line.upper().startswith("TITLE:"):
                title = line.split(":", 1)[1].strip()
            elif line.upper().startswith("BODY:"):
                body = line.split(":", 1)[1].strip()
                # If the body is multi-line, it might be on subsequent lines
                if i + 1 < len(lines) and not lines[i+1].upper().startswith(("TITLE:", "BODY:")):
                    # This is a bit naive but works for simple structures
                    remaining_body = []
                    for next_line in lines[i+1:]:
                        if next_line.upper().startswith(("TITLE:", "BODY:")):
                            break
                        remaining_body.append(next_line)
                    body += " " + " ".join(remaining_body)

        # Fallback if parsing failed
        if not title:
            title = f"Fix issue #{issue_number}"
        if not body:
            body = f"Automated fix generated by vLooper for task {task_id}."

        logger.info("✨ Generated AI PR metadata - Title: %s", title)
        return title, body

    except Exception as e:
        logger.error("Error during AI PR metadata generation: %s", e)

    return f"Fix issue #{issue_number}", f"Automated fix generated by vLooper for task {task_id}."
